'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Gaming")>  _
Partial Public Class MarketingPromosDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertMarketingPromo(instance As MarketingPromo)
    End Sub
  Partial Private Sub UpdateMarketingPromo(instance As MarketingPromo)
    End Sub
  Partial Private Sub DeleteMarketingPromo(instance As MarketingPromo)
    End Sub
  #End Region
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated()
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property MarketingPromos() As System.Data.Linq.Table(Of MarketingPromo)
		Get
			Return Me.GetTable(Of MarketingPromo)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.MarketingPromos")>  _
Partial Public Class MarketingPromo
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _PromoID As Short
	
	Private _PromoName As String
	
	Private _PromoType As String
	
	Private _Query As System.Nullable(Of Short)
	
	Private _PromoDate As System.Nullable(Of Date)
	
	Private _StartDate As System.Nullable(Of Date)
	
	Private _EndDate As System.Nullable(Of Date)
	
	Private _PointCutoff As System.Nullable(Of Short)
	
	Private _PointDivisor As System.Nullable(Of Short)
	
	Private _MaxTickets As System.Nullable(Of Short)
	
	Private _PromoMaxTickets As System.Nullable(Of Short)
	
	Private _MaxCoupon As System.Nullable(Of Decimal)
	
	Private _PromoMaxCoupon As System.Nullable(Of Decimal)
	
	Private _CouponID As String
	
	Private _Recurring As System.Nullable(Of Boolean)
	
	Private _Frequency As System.Nullable(Of Char)
	
	Private _RecursOnWeekday As String
	
	Private _EarnsOnWeekday As String
	
	Private _CountCurrentDay As Boolean
	
	Private _PrintTickets As System.Nullable(Of Boolean)
	
	Private _Comments As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnPromoIDChanging(value As Short)
    End Sub
    Partial Private Sub OnPromoIDChanged()
    End Sub
    Partial Private Sub OnPromoNameChanging(value As String)
    End Sub
    Partial Private Sub OnPromoNameChanged()
    End Sub
    Partial Private Sub OnPromoTypeChanging(value As String)
    End Sub
    Partial Private Sub OnPromoTypeChanged()
    End Sub
    Partial Private Sub OnQueryChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnQueryChanged()
    End Sub
    Partial Private Sub OnPromoDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnPromoDateChanged()
    End Sub
    Partial Private Sub OnStartDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnStartDateChanged()
    End Sub
    Partial Private Sub OnEndDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnEndDateChanged()
    End Sub
    Partial Private Sub OnPointCutoffChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnPointCutoffChanged()
    End Sub
    Partial Private Sub OnPointDivisorChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnPointDivisorChanged()
    End Sub
    Partial Private Sub OnMaxTicketsChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnMaxTicketsChanged()
    End Sub
    Partial Private Sub OnPromoMaxTicketsChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnPromoMaxTicketsChanged()
    End Sub
    Partial Private Sub OnMaxCouponChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnMaxCouponChanged()
    End Sub
    Partial Private Sub OnPromoMaxCouponChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnPromoMaxCouponChanged()
    End Sub
    Partial Private Sub OnCouponIDChanging(value As String)
    End Sub
    Partial Private Sub OnCouponIDChanged()
    End Sub
    Partial Private Sub OnRecurringChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnRecurringChanged()
    End Sub
    Partial Private Sub OnFrequencyChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnFrequencyChanged()
    End Sub
    Partial Private Sub OnRecursOnWeekdayChanging(value As String)
    End Sub
    Partial Private Sub OnRecursOnWeekdayChanged()
    End Sub
    Partial Private Sub OnEarnsOnWeekdayChanging(value As String)
    End Sub
    Partial Private Sub OnEarnsOnWeekdayChanged()
    End Sub
    Partial Private Sub OnCountCurrentDayChanging(value As Boolean)
    End Sub
    Partial Private Sub OnCountCurrentDayChanged()
    End Sub
    Partial Private Sub OnPrintTicketsChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnPrintTicketsChanged()
    End Sub
    Partial Private Sub OnCommentsChanging(value As String)
    End Sub
    Partial Private Sub OnCommentsChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromoID", AutoSync:=AutoSync.OnInsert, DbType:="SmallInt NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property PromoID() As Short
		Get
			Return Me._PromoID
		End Get
		Set
			If ((Me._PromoID = value)  _
						= false) Then
				Me.OnPromoIDChanging(value)
				Me.SendPropertyChanging
				Me._PromoID = value
				Me.SendPropertyChanged("PromoID")
				Me.OnPromoIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromoName", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property PromoName() As String
		Get
			Return Me._PromoName
		End Get
		Set
			If (String.Equals(Me._PromoName, value) = false) Then
				Me.OnPromoNameChanging(value)
				Me.SendPropertyChanging
				Me._PromoName = value
				Me.SendPropertyChanged("PromoName")
				Me.OnPromoNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromoType", DbType:="NVarChar(3)")>  _
	Public Property PromoType() As String
		Get
			Return Me._PromoType
		End Get
		Set
			If (String.Equals(Me._PromoType, value) = false) Then
				Me.OnPromoTypeChanging(value)
				Me.SendPropertyChanging
				Me._PromoType = value
				Me.SendPropertyChanged("PromoType")
				Me.OnPromoTypeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Query", DbType:="SmallInt")>  _
	Public Property Query() As System.Nullable(Of Short)
		Get
			Return Me._Query
		End Get
		Set
			If (Me._Query.Equals(value) = false) Then
				Me.OnQueryChanging(value)
				Me.SendPropertyChanging
				Me._Query = value
				Me.SendPropertyChanged("Query")
				Me.OnQueryChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromoDate", DbType:="DateTime")>  _
	Public Property PromoDate() As System.Nullable(Of Date)
		Get
			Return Me._PromoDate
		End Get
		Set
			If (Me._PromoDate.Equals(value) = false) Then
				Me.OnPromoDateChanging(value)
				Me.SendPropertyChanging
				Me._PromoDate = value
				Me.SendPropertyChanged("PromoDate")
				Me.OnPromoDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StartDate", DbType:="DateTime")>  _
	Public Property StartDate() As System.Nullable(Of Date)
		Get
			Return Me._StartDate
		End Get
		Set
			If (Me._StartDate.Equals(value) = false) Then
				Me.OnStartDateChanging(value)
				Me.SendPropertyChanging
				Me._StartDate = value
				Me.SendPropertyChanged("StartDate")
				Me.OnStartDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EndDate", DbType:="DateTime")>  _
	Public Property EndDate() As System.Nullable(Of Date)
		Get
			Return Me._EndDate
		End Get
		Set
			If (Me._EndDate.Equals(value) = false) Then
				Me.OnEndDateChanging(value)
				Me.SendPropertyChanging
				Me._EndDate = value
				Me.SendPropertyChanged("EndDate")
				Me.OnEndDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PointCutoff", DbType:="SmallInt")>  _
	Public Property PointCutoff() As System.Nullable(Of Short)
		Get
			Return Me._PointCutoff
		End Get
		Set
			If (Me._PointCutoff.Equals(value) = false) Then
				Me.OnPointCutoffChanging(value)
				Me.SendPropertyChanging
				Me._PointCutoff = value
				Me.SendPropertyChanged("PointCutoff")
				Me.OnPointCutoffChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PointDivisor", DbType:="SmallInt")>  _
	Public Property PointDivisor() As System.Nullable(Of Short)
		Get
			Return Me._PointDivisor
		End Get
		Set
			If (Me._PointDivisor.Equals(value) = false) Then
				Me.OnPointDivisorChanging(value)
				Me.SendPropertyChanging
				Me._PointDivisor = value
				Me.SendPropertyChanged("PointDivisor")
				Me.OnPointDivisorChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MaxTickets", DbType:="SmallInt")>  _
	Public Property MaxTickets() As System.Nullable(Of Short)
		Get
			Return Me._MaxTickets
		End Get
		Set
			If (Me._MaxTickets.Equals(value) = false) Then
				Me.OnMaxTicketsChanging(value)
				Me.SendPropertyChanging
				Me._MaxTickets = value
				Me.SendPropertyChanged("MaxTickets")
				Me.OnMaxTicketsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromoMaxTickets", DbType:="SmallInt")>  _
	Public Property PromoMaxTickets() As System.Nullable(Of Short)
		Get
			Return Me._PromoMaxTickets
		End Get
		Set
			If (Me._PromoMaxTickets.Equals(value) = false) Then
				Me.OnPromoMaxTicketsChanging(value)
				Me.SendPropertyChanging
				Me._PromoMaxTickets = value
				Me.SendPropertyChanged("PromoMaxTickets")
				Me.OnPromoMaxTicketsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MaxCoupon", DbType:="SmallMoney")>  _
	Public Property MaxCoupon() As System.Nullable(Of Decimal)
		Get
			Return Me._MaxCoupon
		End Get
		Set
			If (Me._MaxCoupon.Equals(value) = false) Then
				Me.OnMaxCouponChanging(value)
				Me.SendPropertyChanging
				Me._MaxCoupon = value
				Me.SendPropertyChanged("MaxCoupon")
				Me.OnMaxCouponChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromoMaxCoupon", DbType:="SmallMoney")>  _
	Public Property PromoMaxCoupon() As System.Nullable(Of Decimal)
		Get
			Return Me._PromoMaxCoupon
		End Get
		Set
			If (Me._PromoMaxCoupon.Equals(value) = false) Then
				Me.OnPromoMaxCouponChanging(value)
				Me.SendPropertyChanging
				Me._PromoMaxCoupon = value
				Me.SendPropertyChanged("PromoMaxCoupon")
				Me.OnPromoMaxCouponChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CouponID", DbType:="NVarChar(12)")>  _
	Public Property CouponID() As String
		Get
			Return Me._CouponID
		End Get
		Set
			If (String.Equals(Me._CouponID, value) = false) Then
				Me.OnCouponIDChanging(value)
				Me.SendPropertyChanging
				Me._CouponID = value
				Me.SendPropertyChanged("CouponID")
				Me.OnCouponIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Recurring", DbType:="Bit")>  _
	Public Property Recurring() As System.Nullable(Of Boolean)
		Get
			Return Me._Recurring
		End Get
		Set
			If (Me._Recurring.Equals(value) = false) Then
				Me.OnRecurringChanging(value)
				Me.SendPropertyChanging
				Me._Recurring = value
				Me.SendPropertyChanged("Recurring")
				Me.OnRecurringChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Frequency", DbType:="NChar(1)")>  _
	Public Property Frequency() As System.Nullable(Of Char)
		Get
			Return Me._Frequency
		End Get
		Set
			If (Me._Frequency.Equals(value) = false) Then
				Me.OnFrequencyChanging(value)
				Me.SendPropertyChanging
				Me._Frequency = value
				Me.SendPropertyChanged("Frequency")
				Me.OnFrequencyChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RecursOnWeekday", DbType:="NVarChar(7)")>  _
	Public Property RecursOnWeekday() As String
		Get
			Return Me._RecursOnWeekday
		End Get
		Set
			If (String.Equals(Me._RecursOnWeekday, value) = false) Then
				Me.OnRecursOnWeekdayChanging(value)
				Me.SendPropertyChanging
				Me._RecursOnWeekday = value
				Me.SendPropertyChanged("RecursOnWeekday")
				Me.OnRecursOnWeekdayChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EarnsOnWeekday", DbType:="NVarChar(7)")>  _
	Public Property EarnsOnWeekday() As String
		Get
			Return Me._EarnsOnWeekday
		End Get
		Set
			If (String.Equals(Me._EarnsOnWeekday, value) = false) Then
				Me.OnEarnsOnWeekdayChanging(value)
				Me.SendPropertyChanging
				Me._EarnsOnWeekday = value
				Me.SendPropertyChanged("EarnsOnWeekday")
				Me.OnEarnsOnWeekdayChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CountCurrentDay", DbType:="Bit NOT NULL")>  _
	Public Property CountCurrentDay() As Boolean
		Get
			Return Me._CountCurrentDay
		End Get
		Set
			If ((Me._CountCurrentDay = value)  _
						= false) Then
				Me.OnCountCurrentDayChanging(value)
				Me.SendPropertyChanging
				Me._CountCurrentDay = value
				Me.SendPropertyChanged("CountCurrentDay")
				Me.OnCountCurrentDayChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PrintTickets", DbType:="Bit")>  _
	Public Property PrintTickets() As System.Nullable(Of Boolean)
		Get
			Return Me._PrintTickets
		End Get
		Set
			If (Me._PrintTickets.Equals(value) = false) Then
				Me.OnPrintTicketsChanging(value)
				Me.SendPropertyChanging
				Me._PrintTickets = value
				Me.SendPropertyChanged("PrintTickets")
				Me.OnPrintTicketsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Comments", DbType:="NVarChar(255)")>  _
	Public Property Comments() As String
		Get
			Return Me._Comments
		End Get
		Set
			If (String.Equals(Me._Comments, value) = false) Then
				Me.OnCommentsChanging(value)
				Me.SendPropertyChanging
				Me._Comments = value
				Me.SendPropertyChanged("Comments")
				Me.OnCommentsChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
