'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Gaming")>  _
Partial Public Class PCWLINQ2SQLDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertMarketingPromo(instance As MarketingPromo)
    End Sub
  Partial Private Sub UpdateMarketingPromo(instance As MarketingPromo)
    End Sub
  Partial Private Sub DeleteMarketingPromo(instance As MarketingPromo)
    End Sub
  Partial Private Sub InsertMarketingPromoEligiblePlayer(instance As MarketingPromoEligiblePlayer)
    End Sub
  Partial Private Sub UpdateMarketingPromoEligiblePlayer(instance As MarketingPromoEligiblePlayer)
    End Sub
  Partial Private Sub DeleteMarketingPromoEligiblePlayer(instance As MarketingPromoEligiblePlayer)
    End Sub
  Partial Private Sub InsertCouponOffer(instance As CouponOffer)
    End Sub
  Partial Private Sub UpdateCouponOffer(instance As CouponOffer)
    End Sub
  Partial Private Sub DeleteCouponOffer(instance As CouponOffer)
    End Sub
  Partial Private Sub InsertCouponTarget(instance As CouponTarget)
    End Sub
  Partial Private Sub UpdateCouponTarget(instance As CouponTarget)
    End Sub
  Partial Private Sub DeleteCouponTarget(instance As CouponTarget)
    End Sub
  #End Region
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property MarketingPromos() As System.Data.Linq.Table(Of MarketingPromo)
		Get
			Return Me.GetTable(Of MarketingPromo)
		End Get
	End Property
	
	Public ReadOnly Property MarketingPromoEligiblePlayers() As System.Data.Linq.Table(Of MarketingPromoEligiblePlayer)
		Get
			Return Me.GetTable(Of MarketingPromoEligiblePlayer)
		End Get
	End Property
	
	Public ReadOnly Property CouponOffers() As System.Data.Linq.Table(Of CouponOffer)
		Get
			Return Me.GetTable(Of CouponOffer)
		End Get
	End Property
	
	Public ReadOnly Property CouponTargets() As System.Data.Linq.Table(Of CouponTarget)
		Get
			Return Me.GetTable(Of CouponTarget)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.MarketingPromos")>  _
Partial Public Class MarketingPromo
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _PromoID As String
	
	Private _PromoName As String
	
	Private _PromoType As String
	
	Private _PromoDate As System.Nullable(Of Date)
	
	Private _StartDate As System.Nullable(Of Date)
	
	Private _EndDate As System.Nullable(Of Date)
	
	Private _PointCutoff As System.Nullable(Of Short)
	
	Private _PointDivisor As System.Nullable(Of Short)
	
	Private _MaxTickets As System.Nullable(Of Short)
	
	Private _PromoMaxTickets As System.Nullable(Of Short)
	
	Private _MaxCoupon As System.Nullable(Of Decimal)
	
	Private _PromoMaxCoupon As System.Nullable(Of Decimal)
	
	Private _CouponID As String
	
	Private _Recurring As System.Nullable(Of Boolean)
	
	Private _Frequency As System.Nullable(Of Char)
	
	Private _RecursOnWeekday As String
	
	Private _EarnsOnWeekday As String
	
	Private _CountCurrentDay As Boolean
	
	Private _OverrideTime As String
	
	Private _CutoffTime As String
	
	Private _PrintTickets As System.Nullable(Of Boolean)
	
	Private _Comments As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnPromoIDChanging(value As String)
    End Sub
    Partial Private Sub OnPromoIDChanged()
    End Sub
    Partial Private Sub OnPromoNameChanging(value As String)
    End Sub
    Partial Private Sub OnPromoNameChanged()
    End Sub
    Partial Private Sub OnPromoTypeChanging(value As String)
    End Sub
    Partial Private Sub OnPromoTypeChanged()
    End Sub
    Partial Private Sub OnPromoDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnPromoDateChanged()
    End Sub
    Partial Private Sub OnStartDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnStartDateChanged()
    End Sub
    Partial Private Sub OnEndDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnEndDateChanged()
    End Sub
    Partial Private Sub OnPointCutoffChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnPointCutoffChanged()
    End Sub
    Partial Private Sub OnPointDivisorChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnPointDivisorChanged()
    End Sub
    Partial Private Sub OnMaxTicketsChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnMaxTicketsChanged()
    End Sub
    Partial Private Sub OnPromoMaxTicketsChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnPromoMaxTicketsChanged()
    End Sub
    Partial Private Sub OnMaxCouponChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnMaxCouponChanged()
    End Sub
    Partial Private Sub OnPromoMaxCouponChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnPromoMaxCouponChanged()
    End Sub
    Partial Private Sub OnCouponIDChanging(value As String)
    End Sub
    Partial Private Sub OnCouponIDChanged()
    End Sub
    Partial Private Sub OnRecurringChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnRecurringChanged()
    End Sub
    Partial Private Sub OnFrequencyChanging(value As System.Nullable(Of Char))
    End Sub
    Partial Private Sub OnFrequencyChanged()
    End Sub
    Partial Private Sub OnRecursOnWeekdayChanging(value As String)
    End Sub
    Partial Private Sub OnRecursOnWeekdayChanged()
    End Sub
    Partial Private Sub OnEarnsOnWeekdayChanging(value As String)
    End Sub
    Partial Private Sub OnEarnsOnWeekdayChanged()
    End Sub
    Partial Private Sub OnCountCurrentDayChanging(value As Boolean)
    End Sub
    Partial Private Sub OnCountCurrentDayChanged()
    End Sub
    Partial Private Sub OnOverrideTimeChanging(value As String)
    End Sub
    Partial Private Sub OnOverrideTimeChanged()
    End Sub
    Partial Private Sub OnCutoffTimeChanging(value As String)
    End Sub
    Partial Private Sub OnCutoffTimeChanged()
    End Sub
    Partial Private Sub OnPrintTicketsChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnPrintTicketsChanged()
    End Sub
    Partial Private Sub OnCommentsChanging(value As String)
    End Sub
    Partial Private Sub OnCommentsChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromoID", DbType:="NVarChar(16) NOT NULL IDENTITY", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property PromoID() As String
		Get
			Return Me._PromoID
		End Get
		Set
			If (String.Equals(Me._PromoID, value) = false) Then
				Me.OnPromoIDChanging(value)
				Me.SendPropertyChanging
				Me._PromoID = value
				Me.SendPropertyChanged("PromoID")
				Me.OnPromoIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromoName", DbType:="NVarChar(50) NOT NULL", CanBeNull:=false)>  _
	Public Property PromoName() As String
		Get
			Return Me._PromoName
		End Get
		Set
			If (String.Equals(Me._PromoName, value) = false) Then
				Me.OnPromoNameChanging(value)
				Me.SendPropertyChanging
				Me._PromoName = value
				Me.SendPropertyChanged("PromoName")
				Me.OnPromoNameChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromoType", DbType:="NVarChar(3)")>  _
	Public Property PromoType() As String
		Get
			Return Me._PromoType
		End Get
		Set
			If (String.Equals(Me._PromoType, value) = false) Then
				Me.OnPromoTypeChanging(value)
				Me.SendPropertyChanging
				Me._PromoType = value
				Me.SendPropertyChanged("PromoType")
				Me.OnPromoTypeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromoDate", DbType:="DateTime")>  _
	Public Property PromoDate() As System.Nullable(Of Date)
		Get
			Return Me._PromoDate
		End Get
		Set
			If (Me._PromoDate.Equals(value) = false) Then
				Me.OnPromoDateChanging(value)
				Me.SendPropertyChanging
				Me._PromoDate = value
				Me.SendPropertyChanged("PromoDate")
				Me.OnPromoDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StartDate", DbType:="DateTime")>  _
	Public Property StartDate() As System.Nullable(Of Date)
		Get
			Return Me._StartDate
		End Get
		Set
			If (Me._StartDate.Equals(value) = false) Then
				Me.OnStartDateChanging(value)
				Me.SendPropertyChanging
				Me._StartDate = value
				Me.SendPropertyChanged("StartDate")
				Me.OnStartDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EndDate", DbType:="DateTime")>  _
	Public Property EndDate() As System.Nullable(Of Date)
		Get
			Return Me._EndDate
		End Get
		Set
			If (Me._EndDate.Equals(value) = false) Then
				Me.OnEndDateChanging(value)
				Me.SendPropertyChanging
				Me._EndDate = value
				Me.SendPropertyChanged("EndDate")
				Me.OnEndDateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PointCutoff", DbType:="SmallInt")>  _
	Public Property PointCutoff() As System.Nullable(Of Short)
		Get
			Return Me._PointCutoff
		End Get
		Set
			If (Me._PointCutoff.Equals(value) = false) Then
				Me.OnPointCutoffChanging(value)
				Me.SendPropertyChanging
				Me._PointCutoff = value
				Me.SendPropertyChanged("PointCutoff")
				Me.OnPointCutoffChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PointDivisor", DbType:="SmallInt")>  _
	Public Property PointDivisor() As System.Nullable(Of Short)
		Get
			Return Me._PointDivisor
		End Get
		Set
			If (Me._PointDivisor.Equals(value) = false) Then
				Me.OnPointDivisorChanging(value)
				Me.SendPropertyChanging
				Me._PointDivisor = value
				Me.SendPropertyChanged("PointDivisor")
				Me.OnPointDivisorChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MaxTickets", DbType:="SmallInt")>  _
	Public Property MaxTickets() As System.Nullable(Of Short)
		Get
			Return Me._MaxTickets
		End Get
		Set
			If (Me._MaxTickets.Equals(value) = false) Then
				Me.OnMaxTicketsChanging(value)
				Me.SendPropertyChanging
				Me._MaxTickets = value
				Me.SendPropertyChanged("MaxTickets")
				Me.OnMaxTicketsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromoMaxTickets", DbType:="SmallInt")>  _
	Public Property PromoMaxTickets() As System.Nullable(Of Short)
		Get
			Return Me._PromoMaxTickets
		End Get
		Set
			If (Me._PromoMaxTickets.Equals(value) = false) Then
				Me.OnPromoMaxTicketsChanging(value)
				Me.SendPropertyChanging
				Me._PromoMaxTickets = value
				Me.SendPropertyChanged("PromoMaxTickets")
				Me.OnPromoMaxTicketsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MaxCoupon", DbType:="SmallMoney")>  _
	Public Property MaxCoupon() As System.Nullable(Of Decimal)
		Get
			Return Me._MaxCoupon
		End Get
		Set
			If (Me._MaxCoupon.Equals(value) = false) Then
				Me.OnMaxCouponChanging(value)
				Me.SendPropertyChanging
				Me._MaxCoupon = value
				Me.SendPropertyChanged("MaxCoupon")
				Me.OnMaxCouponChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromoMaxCoupon", DbType:="SmallMoney")>  _
	Public Property PromoMaxCoupon() As System.Nullable(Of Decimal)
		Get
			Return Me._PromoMaxCoupon
		End Get
		Set
			If (Me._PromoMaxCoupon.Equals(value) = false) Then
				Me.OnPromoMaxCouponChanging(value)
				Me.SendPropertyChanging
				Me._PromoMaxCoupon = value
				Me.SendPropertyChanged("PromoMaxCoupon")
				Me.OnPromoMaxCouponChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CouponID", DbType:="NVarChar(12)")>  _
	Public Property CouponID() As String
		Get
			Return Me._CouponID
		End Get
		Set
			If (String.Equals(Me._CouponID, value) = false) Then
				Me.OnCouponIDChanging(value)
				Me.SendPropertyChanging
				Me._CouponID = value
				Me.SendPropertyChanged("CouponID")
				Me.OnCouponIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Recurring", DbType:="Bit")>  _
	Public Property Recurring() As System.Nullable(Of Boolean)
		Get
			Return Me._Recurring
		End Get
		Set
			If (Me._Recurring.Equals(value) = false) Then
				Me.OnRecurringChanging(value)
				Me.SendPropertyChanging
				Me._Recurring = value
				Me.SendPropertyChanged("Recurring")
				Me.OnRecurringChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Frequency", DbType:="NChar(1)")>  _
	Public Property Frequency() As System.Nullable(Of Char)
		Get
			Return Me._Frequency
		End Get
		Set
			If (Me._Frequency.Equals(value) = false) Then
				Me.OnFrequencyChanging(value)
				Me.SendPropertyChanging
				Me._Frequency = value
				Me.SendPropertyChanged("Frequency")
				Me.OnFrequencyChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RecursOnWeekday", DbType:="NVarChar(7)")>  _
	Public Property RecursOnWeekday() As String
		Get
			Return Me._RecursOnWeekday
		End Get
		Set
			If (String.Equals(Me._RecursOnWeekday, value) = false) Then
				Me.OnRecursOnWeekdayChanging(value)
				Me.SendPropertyChanging
				Me._RecursOnWeekday = value
				Me.SendPropertyChanged("RecursOnWeekday")
				Me.OnRecursOnWeekdayChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EarnsOnWeekday", DbType:="NVarChar(7)")>  _
	Public Property EarnsOnWeekday() As String
		Get
			Return Me._EarnsOnWeekday
		End Get
		Set
			If (String.Equals(Me._EarnsOnWeekday, value) = false) Then
				Me.OnEarnsOnWeekdayChanging(value)
				Me.SendPropertyChanging
				Me._EarnsOnWeekday = value
				Me.SendPropertyChanged("EarnsOnWeekday")
				Me.OnEarnsOnWeekdayChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CountCurrentDay", DbType:="Bit NOT NULL")>  _
	Public Property CountCurrentDay() As Boolean
		Get
			Return Me._CountCurrentDay
		End Get
		Set
			If ((Me._CountCurrentDay = value)  _
						= false) Then
				Me.OnCountCurrentDayChanging(value)
				Me.SendPropertyChanging
				Me._CountCurrentDay = value
				Me.SendPropertyChanged("CountCurrentDay")
				Me.OnCountCurrentDayChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OverrideTime", DbType:="NChar(5)")>  _
	Public Property OverrideTime() As String
		Get
			Return Me._OverrideTime
		End Get
		Set
			If (String.Equals(Me._OverrideTime, value) = false) Then
				Me.OnOverrideTimeChanging(value)
				Me.SendPropertyChanging
				Me._OverrideTime = value
				Me.SendPropertyChanged("OverrideTime")
				Me.OnOverrideTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CutoffTime", DbType:="NChar(5)")>  _
	Public Property CutoffTime() As String
		Get
			Return Me._CutoffTime
		End Get
		Set
			If (String.Equals(Me._CutoffTime, value) = false) Then
				Me.OnCutoffTimeChanging(value)
				Me.SendPropertyChanging
				Me._CutoffTime = value
				Me.SendPropertyChanged("CutoffTime")
				Me.OnCutoffTimeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PrintTickets", DbType:="Bit")>  _
	Public Property PrintTickets() As System.Nullable(Of Boolean)
		Get
			Return Me._PrintTickets
		End Get
		Set
			If (Me._PrintTickets.Equals(value) = false) Then
				Me.OnPrintTicketsChanging(value)
				Me.SendPropertyChanging
				Me._PrintTickets = value
				Me.SendPropertyChanged("PrintTickets")
				Me.OnPrintTicketsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Comments", DbType:="NVarChar(255)")>  _
	Public Property Comments() As String
		Get
			Return Me._Comments
		End Get
		Set
			If (String.Equals(Me._Comments, value) = false) Then
				Me.OnCommentsChanging(value)
				Me.SendPropertyChanging
				Me._Comments = value
				Me.SendPropertyChanged("Comments")
				Me.OnCommentsChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.MarketingPromoEligiblePlayers")>  _
Partial Public Class MarketingPromoEligiblePlayer
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _PromoID As String
	
	Private _PlayerID As Integer
	
	Private _NumOfTickets As System.Nullable(Of Short)
	
	Private _TicketAmount As System.Nullable(Of Decimal)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnPromoIDChanging(value As String)
    End Sub
    Partial Private Sub OnPromoIDChanged()
    End Sub
    Partial Private Sub OnPlayerIDChanging(value As Integer)
    End Sub
    Partial Private Sub OnPlayerIDChanged()
    End Sub
    Partial Private Sub OnNumOfTicketsChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnNumOfTicketsChanged()
    End Sub
    Partial Private Sub OnTicketAmountChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnTicketAmountChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PromoID", DbType:="NVarChar(16) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property PromoID() As String
		Get
			Return Me._PromoID
		End Get
		Set
			If (String.Equals(Me._PromoID, value) = false) Then
				Me.OnPromoIDChanging(value)
				Me.SendPropertyChanging
				Me._PromoID = value
				Me.SendPropertyChanged("PromoID")
				Me.OnPromoIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PlayerID", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property PlayerID() As Integer
		Get
			Return Me._PlayerID
		End Get
		Set
			If ((Me._PlayerID = value)  _
						= false) Then
				Me.OnPlayerIDChanging(value)
				Me.SendPropertyChanging
				Me._PlayerID = value
				Me.SendPropertyChanged("PlayerID")
				Me.OnPlayerIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NumOfTickets", DbType:="SmallInt")>  _
	Public Property NumOfTickets() As System.Nullable(Of Short)
		Get
			Return Me._NumOfTickets
		End Get
		Set
			If (Me._NumOfTickets.Equals(value) = false) Then
				Me.OnNumOfTicketsChanging(value)
				Me.SendPropertyChanging
				Me._NumOfTickets = value
				Me.SendPropertyChanged("NumOfTickets")
				Me.OnNumOfTicketsChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TicketAmount", DbType:="Money")>  _
	Public Property TicketAmount() As System.Nullable(Of Decimal)
		Get
			Return Me._TicketAmount
		End Get
		Set
			If (Me._TicketAmount.Equals(value) = false) Then
				Me.OnTicketAmountChanging(value)
				Me.SendPropertyChanging
				Me._TicketAmount = value
				Me.SendPropertyChanged("TicketAmount")
				Me.OnTicketAmountChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.CouponOffers")>  _
Partial Public Class CouponOffer
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _OfferID As String
	
	Private _CouponNumber As Byte
	
	Private _ValidStart As Date
	
	Private _ValidEnd As Date
	
	Private _ExcludeDays As String
	
	Private _ExcludeStart As System.Nullable(Of Date)
	
	Private _ExcludeEnd As System.Nullable(Of Date)
	
	Private _FullValidate As System.Nullable(Of Boolean)
	
	Private _Reprintable As Boolean
	
	Private _ScanToReceipt As Boolean
	
	Private _Note As String
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnOfferIDChanging(value As String)
    End Sub
    Partial Private Sub OnOfferIDChanged()
    End Sub
    Partial Private Sub OnCouponNumberChanging(value As Byte)
    End Sub
    Partial Private Sub OnCouponNumberChanged()
    End Sub
    Partial Private Sub OnValidStartChanging(value As Date)
    End Sub
    Partial Private Sub OnValidStartChanged()
    End Sub
    Partial Private Sub OnValidEndChanging(value As Date)
    End Sub
    Partial Private Sub OnValidEndChanged()
    End Sub
    Partial Private Sub OnExcludeDaysChanging(value As String)
    End Sub
    Partial Private Sub OnExcludeDaysChanged()
    End Sub
    Partial Private Sub OnExcludeStartChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnExcludeStartChanged()
    End Sub
    Partial Private Sub OnExcludeEndChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnExcludeEndChanged()
    End Sub
    Partial Private Sub OnFullValidateChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnFullValidateChanged()
    End Sub
    Partial Private Sub OnReprintableChanging(value As Boolean)
    End Sub
    Partial Private Sub OnReprintableChanged()
    End Sub
    Partial Private Sub OnScanToReceiptChanging(value As Boolean)
    End Sub
    Partial Private Sub OnScanToReceiptChanged()
    End Sub
    Partial Private Sub OnNoteChanging(value As String)
    End Sub
    Partial Private Sub OnNoteChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OfferID", DbType:="NVarChar(12) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property OfferID() As String
		Get
			Return Me._OfferID
		End Get
		Set
			If (String.Equals(Me._OfferID, value) = false) Then
				Me.OnOfferIDChanging(value)
				Me.SendPropertyChanging
				Me._OfferID = value
				Me.SendPropertyChanged("OfferID")
				Me.OnOfferIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CouponNumber", DbType:="TinyInt NOT NULL", IsPrimaryKey:=true)>  _
	Public Property CouponNumber() As Byte
		Get
			Return Me._CouponNumber
		End Get
		Set
			If ((Me._CouponNumber = value)  _
						= false) Then
				Me.OnCouponNumberChanging(value)
				Me.SendPropertyChanging
				Me._CouponNumber = value
				Me.SendPropertyChanged("CouponNumber")
				Me.OnCouponNumberChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValidStart", DbType:="SmallDateTime NOT NULL")>  _
	Public Property ValidStart() As Date
		Get
			Return Me._ValidStart
		End Get
		Set
			If ((Me._ValidStart = value)  _
						= false) Then
				Me.OnValidStartChanging(value)
				Me.SendPropertyChanging
				Me._ValidStart = value
				Me.SendPropertyChanged("ValidStart")
				Me.OnValidStartChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ValidEnd", DbType:="SmallDateTime NOT NULL")>  _
	Public Property ValidEnd() As Date
		Get
			Return Me._ValidEnd
		End Get
		Set
			If ((Me._ValidEnd = value)  _
						= false) Then
				Me.OnValidEndChanging(value)
				Me.SendPropertyChanging
				Me._ValidEnd = value
				Me.SendPropertyChanged("ValidEnd")
				Me.OnValidEndChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ExcludeDays", DbType:="NVarChar(7)")>  _
	Public Property ExcludeDays() As String
		Get
			Return Me._ExcludeDays
		End Get
		Set
			If (String.Equals(Me._ExcludeDays, value) = false) Then
				Me.OnExcludeDaysChanging(value)
				Me.SendPropertyChanging
				Me._ExcludeDays = value
				Me.SendPropertyChanged("ExcludeDays")
				Me.OnExcludeDaysChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ExcludeStart", DbType:="SmallDateTime")>  _
	Public Property ExcludeStart() As System.Nullable(Of Date)
		Get
			Return Me._ExcludeStart
		End Get
		Set
			If (Me._ExcludeStart.Equals(value) = false) Then
				Me.OnExcludeStartChanging(value)
				Me.SendPropertyChanging
				Me._ExcludeStart = value
				Me.SendPropertyChanged("ExcludeStart")
				Me.OnExcludeStartChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ExcludeEnd", DbType:="SmallDateTime")>  _
	Public Property ExcludeEnd() As System.Nullable(Of Date)
		Get
			Return Me._ExcludeEnd
		End Get
		Set
			If (Me._ExcludeEnd.Equals(value) = false) Then
				Me.OnExcludeEndChanging(value)
				Me.SendPropertyChanging
				Me._ExcludeEnd = value
				Me.SendPropertyChanged("ExcludeEnd")
				Me.OnExcludeEndChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FullValidate", DbType:="Bit")>  _
	Public Property FullValidate() As System.Nullable(Of Boolean)
		Get
			Return Me._FullValidate
		End Get
		Set
			If (Me._FullValidate.Equals(value) = false) Then
				Me.OnFullValidateChanging(value)
				Me.SendPropertyChanging
				Me._FullValidate = value
				Me.SendPropertyChanged("FullValidate")
				Me.OnFullValidateChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Reprintable", DbType:="Bit NOT NULL")>  _
	Public Property Reprintable() As Boolean
		Get
			Return Me._Reprintable
		End Get
		Set
			If ((Me._Reprintable = value)  _
						= false) Then
				Me.OnReprintableChanging(value)
				Me.SendPropertyChanging
				Me._Reprintable = value
				Me.SendPropertyChanged("Reprintable")
				Me.OnReprintableChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ScanToReceipt", DbType:="Bit NOT NULL")>  _
	Public Property ScanToReceipt() As Boolean
		Get
			Return Me._ScanToReceipt
		End Get
		Set
			If ((Me._ScanToReceipt = value)  _
						= false) Then
				Me.OnScanToReceiptChanging(value)
				Me.SendPropertyChanging
				Me._ScanToReceipt = value
				Me.SendPropertyChanged("ScanToReceipt")
				Me.OnScanToReceiptChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Note", DbType:="NVarChar(50)")>  _
	Public Property Note() As String
		Get
			Return Me._Note
		End Get
		Set
			If (String.Equals(Me._Note, value) = false) Then
				Me.OnNoteChanging(value)
				Me.SendPropertyChanging
				Me._Note = value
				Me.SendPropertyChanged("Note")
				Me.OnNoteChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.CouponTargets")>  _
Partial Public Class CouponTarget
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _OfferID As String
	
	Private _Coupon As Byte
	
	Private _Account As Integer
	
	Private _Zip As String
	
	Private _AvgTheo As System.Nullable(Of Decimal)
	
	Private _Latency As System.Nullable(Of Decimal)
	
	Private _BaseCoupon As System.Nullable(Of Decimal)
	
	Private _ZoneAddon As System.Nullable(Of Decimal)
	
	Private _OtherAddon As System.Nullable(Of Decimal)
	
	Private _TotalCoupon As Decimal
	
	Private _TestCoupon As System.Nullable(Of Boolean)
	
	Private _CreateDate As System.Nullable(Of Date)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnOfferIDChanging(value As String)
    End Sub
    Partial Private Sub OnOfferIDChanged()
    End Sub
    Partial Private Sub OnCouponChanging(value As Byte)
    End Sub
    Partial Private Sub OnCouponChanged()
    End Sub
    Partial Private Sub OnAccountChanging(value As Integer)
    End Sub
    Partial Private Sub OnAccountChanged()
    End Sub
    Partial Private Sub OnZipChanging(value As String)
    End Sub
    Partial Private Sub OnZipChanged()
    End Sub
    Partial Private Sub OnAvgTheoChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnAvgTheoChanged()
    End Sub
    Partial Private Sub OnLatencyChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnLatencyChanged()
    End Sub
    Partial Private Sub OnBaseCouponChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnBaseCouponChanged()
    End Sub
    Partial Private Sub OnZoneAddonChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnZoneAddonChanged()
    End Sub
    Partial Private Sub OnOtherAddonChanging(value As System.Nullable(Of Decimal))
    End Sub
    Partial Private Sub OnOtherAddonChanged()
    End Sub
    Partial Private Sub OnTotalCouponChanging(value As Decimal)
    End Sub
    Partial Private Sub OnTotalCouponChanged()
    End Sub
    Partial Private Sub OnTestCouponChanging(value As System.Nullable(Of Boolean))
    End Sub
    Partial Private Sub OnTestCouponChanged()
    End Sub
    Partial Private Sub OnCreateDateChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCreateDateChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OfferID", DbType:="NVarChar(10) NOT NULL", CanBeNull:=false, IsPrimaryKey:=true)>  _
	Public Property OfferID() As String
		Get
			Return Me._OfferID
		End Get
		Set
			If (String.Equals(Me._OfferID, value) = false) Then
				Me.OnOfferIDChanging(value)
				Me.SendPropertyChanging
				Me._OfferID = value
				Me.SendPropertyChanged("OfferID")
				Me.OnOfferIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Coupon", DbType:="TinyInt NOT NULL", IsPrimaryKey:=true)>  _
	Public Property Coupon() As Byte
		Get
			Return Me._Coupon
		End Get
		Set
			If ((Me._Coupon = value)  _
						= false) Then
				Me.OnCouponChanging(value)
				Me.SendPropertyChanging
				Me._Coupon = value
				Me.SendPropertyChanged("Coupon")
				Me.OnCouponChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Account", DbType:="Int NOT NULL", IsPrimaryKey:=true)>  _
	Public Property Account() As Integer
		Get
			Return Me._Account
		End Get
		Set
			If ((Me._Account = value)  _
						= false) Then
				Me.OnAccountChanging(value)
				Me.SendPropertyChanging
				Me._Account = value
				Me.SendPropertyChanged("Account")
				Me.OnAccountChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Zip", DbType:="NVarChar(10)")>  _
	Public Property Zip() As String
		Get
			Return Me._Zip
		End Get
		Set
			If (String.Equals(Me._Zip, value) = false) Then
				Me.OnZipChanging(value)
				Me.SendPropertyChanging
				Me._Zip = value
				Me.SendPropertyChanged("Zip")
				Me.OnZipChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_AvgTheo", DbType:="SmallMoney")>  _
	Public Property AvgTheo() As System.Nullable(Of Decimal)
		Get
			Return Me._AvgTheo
		End Get
		Set
			If (Me._AvgTheo.Equals(value) = false) Then
				Me.OnAvgTheoChanging(value)
				Me.SendPropertyChanging
				Me._AvgTheo = value
				Me.SendPropertyChanged("AvgTheo")
				Me.OnAvgTheoChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Latency", DbType:="Decimal(5,0)")>  _
	Public Property Latency() As System.Nullable(Of Decimal)
		Get
			Return Me._Latency
		End Get
		Set
			If (Me._Latency.Equals(value) = false) Then
				Me.OnLatencyChanging(value)
				Me.SendPropertyChanging
				Me._Latency = value
				Me.SendPropertyChanged("Latency")
				Me.OnLatencyChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_BaseCoupon", DbType:="SmallMoney")>  _
	Public Property BaseCoupon() As System.Nullable(Of Decimal)
		Get
			Return Me._BaseCoupon
		End Get
		Set
			If (Me._BaseCoupon.Equals(value) = false) Then
				Me.OnBaseCouponChanging(value)
				Me.SendPropertyChanging
				Me._BaseCoupon = value
				Me.SendPropertyChanged("BaseCoupon")
				Me.OnBaseCouponChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ZoneAddon", DbType:="SmallMoney")>  _
	Public Property ZoneAddon() As System.Nullable(Of Decimal)
		Get
			Return Me._ZoneAddon
		End Get
		Set
			If (Me._ZoneAddon.Equals(value) = false) Then
				Me.OnZoneAddonChanging(value)
				Me.SendPropertyChanging
				Me._ZoneAddon = value
				Me.SendPropertyChanged("ZoneAddon")
				Me.OnZoneAddonChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OtherAddon", DbType:="SmallMoney")>  _
	Public Property OtherAddon() As System.Nullable(Of Decimal)
		Get
			Return Me._OtherAddon
		End Get
		Set
			If (Me._OtherAddon.Equals(value) = false) Then
				Me.OnOtherAddonChanging(value)
				Me.SendPropertyChanging
				Me._OtherAddon = value
				Me.SendPropertyChanged("OtherAddon")
				Me.OnOtherAddonChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TotalCoupon", DbType:="SmallMoney NOT NULL")>  _
	Public Property TotalCoupon() As Decimal
		Get
			Return Me._TotalCoupon
		End Get
		Set
			If ((Me._TotalCoupon = value)  _
						= false) Then
				Me.OnTotalCouponChanging(value)
				Me.SendPropertyChanging
				Me._TotalCoupon = value
				Me.SendPropertyChanged("TotalCoupon")
				Me.OnTotalCouponChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TestCoupon", DbType:="Bit")>  _
	Public Property TestCoupon() As System.Nullable(Of Boolean)
		Get
			Return Me._TestCoupon
		End Get
		Set
			If (Me._TestCoupon.Equals(value) = false) Then
				Me.OnTestCouponChanging(value)
				Me.SendPropertyChanging
				Me._TestCoupon = value
				Me.SendPropertyChanged("TestCoupon")
				Me.OnTestCouponChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CreateDate", DbType:="DateTime")>  _
	Public Property CreateDate() As System.Nullable(Of Date)
		Get
			Return Me._CreateDate
		End Get
		Set
			If (Me._CreateDate.Equals(value) = false) Then
				Me.OnCreateDateChanging(value)
				Me.SendPropertyChanging
				Me._CreateDate = value
				Me.SendPropertyChanged("CreateDate")
				Me.OnCreateDateChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
